# Generated by Django 6.0.5 on 2026-06-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_author_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
